package seed

import (
	"context"
	"log"
	"time"

	"github.com/AlexBetita/go_prac/internal/models"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

func SeedPosts(ctx context.Context, db *mongo.Database) error {
	postsCollection := db.Collection("posts")

	now := time.Now().Unix()
	posts := []interface{}{
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "10 Ways Go Will Change Your Life", Content: "Go isn’t just for servers—it’s a lifestyle. Discover how Go will revolutionize your coding zen.", Summary: "Life hacks, the Go way.", Message: "go life hacks", Keywords: []string{"golang", "productivity", "dev"}, Tags: []string{"Tech", "Life"}, Slug: "go-changes-life", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Debugging With Ducks", Content: "Ever tried explaining your bug to a rubber duck? Let’s get weird—and productive.", Summary: "Rubber duck debugging, demystified.", Message: "explain duck debugging", Keywords: []string{"debugging", "tips"}, Tags: []string{"Education", "Tech"}, Slug: "debugging-with-ducks", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "How MongoDB Is Like a Fridge", Content: "It stores your stuff, sometimes smells weird, and you always forget what’s in it.", Summary: "Database metaphors that work.", Message: "mongodb is fridge", Keywords: []string{"mongodb", "databases"}, Tags: []string{"Tech", "Life"}, Slug: "mongodb-fridge", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "API Rage: A Dev's Therapy Guide", Content: "We’ve all screamed at a 500 error. Here's how to heal your relationship with REST.", Summary: "When endpoints end you.", Message: "api therapy", Keywords: []string{"api", "errors", "rest"}, Tags: []string{"Health", "Tech"}, Slug: "api-rage-guide", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Why My Code Needs Therapy", Content: "If your functions had feelings, they'd be crying. Let's unpack that.", Summary: "An emotional journey through tech debt.", Message: "code needs therapy", Keywords: []string{"mental health", "code", "tech debt"}, Tags: []string{"Health", "Life"}, Slug: "code-therapy", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Frontend Frameworks Rated by Pizza", Content: "React? Thin crust. Svelte? Artisan wood-fired. Angular? Deep dish with extra sauce.", Summary: "Deliciously subjective tech takes.", Message: "frameworks pizza rating", Keywords: []string{"frontend", "frameworks", "fun"}, Tags: []string{"Entertainment", "Tech"}, Slug: "frameworks-pizza", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "The AI That Writes Poetry... Poorly", Content: "We gave GPT a thesaurus and asked for Shakespeare. Here's what happened.", Summary: "Machine learning meets bad haiku.", Message: "ai writes poetry", Keywords: []string{"ai", "gpt", "poetry"}, Tags: []string{"Art", "Tech"}, Slug: "ai-poetry-fail", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "You Don't Need a Database, You Need a Nap", Content: "Before scaling with microservices, maybe sleep?", Summary: "Rest before REST.", Message: "nap before scaling", Keywords: []string{"dev", "rest", "overengineering"}, Tags: []string{"Health", "Tech"}, Slug: "database-vs-nap", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "GraphQL: Choose Your Own Adventure", Content: "It’s like REST, but with multiple endings.", Summary: "GraphQL explained in gaming terms.", Message: "graphql adventure", Keywords: []string{"graphql", "api"}, Tags: []string{"Education", "Tech"}, Slug: "graphql-adventure", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "99 Problems But a Script Ain't One", Content: "Automate all the boring stuff and some of the fun stuff too.", Summary: "Your terminal is a vibe.", Message: "funny scripting tips", Keywords: []string{"automation", "scripts"}, Tags: []string{"Tech", "Business"}, Slug: "99-script-problems", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Dark Mode Devs vs Light Mode Rebels", Content: "A tale of two IDEs. Only one can win. Or can they?", Summary: "Light vs dark: the real war.", Message: "light vs dark mode devs", Keywords: []string{"ide", "themes", "productivity"}, Tags: []string{"Life", "Tech"}, Slug: "dark-vs-light", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Traveling as a Remote Dev: Dream or Distraction?", Content: "Coding with a view sounds nice until the Wi-Fi cuts out mid-deploy.", Summary: "Life on the road as a remote worker.", Message: "digital nomad pros and cons", Keywords: []string{"remote", "travel", "wifi"}, Tags: []string{"Travel", "Life"}, Slug: "remote-dev-travel", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "AI Replaced My Boss. Should I Be Scared?", Content: "Or should I just get better at prompt engineering?", Summary: "AI in the workplace, explained.", Message: "ai management roles", Keywords: []string{"ai", "jobs", "automation"}, Tags: []string{"Business", "News"}, Slug: "ai-boss", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Why Coffee is the Greatest IDE Plugin", Content: "It doesn’t autocomplete, but it powers everything.", Summary: "Coffee-driven development.", Message: "coffee for devs", Keywords: []string{"coffee", "focus"}, Tags: []string{"Health", "Tech"}, Slug: "coffee-plugin", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Quantum Computing Explained with Cats", Content: "Schrödinger’s Server is both up and down until you ping it.", Summary: "Fun with quantum logic.", Message: "quantum computing fun analogy", Keywords: []string{"quantum", "science", "fun"}, Tags: []string{"Science", "Education"}, Slug: "quantum-cats", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Art in the Age of Algorithms", Content: "Can machines be creative? Let’s explore how AI and artists are colliding in the digital world.", Summary: "Creativity meets computation.", Message: "ai and art", Keywords: []string{"ai", "creativity", "art"}, Tags: []string{"Art", "Tech"}, Slug: "ai-art-era", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Tech News You Can Actually Use", Content: "Forget the buzzwords. Here's the tech news that matters to your work today.", Summary: "Signal over noise in the tech world.", Message: "useful tech news", Keywords: []string{"tech", "news", "tools"}, Tags: []string{"News", "Tech"}, Slug: "practical-tech-news", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "From Burnout to Breakthrough", Content: "A personal journey of leaving crunch culture and finding balance in code.", Summary: "Healing through boundaries and structure.", Message: "burnout recovery", Keywords: []string{"burnout", "health", "tech"}, Tags: []string{"Health", "Life"}, Slug: "burnout-breakthrough", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "What If Planets Had Operating Systems?", Content: "Earth runs on Linux, Mars on RustOS, and Mercury is clearly a beta build.", Summary: "Sci-fi meets system design.", Message: "planets as operating systems", Keywords: []string{"science", "systems"}, Tags: []string{"Science", "Entertainment"}, Slug: "planet-os-theory", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Coding Horror Stories from the Trenches", Content: "I once deployed to production on a Friday. Here's how I survived.", Summary: "Tales of disaster and recovery.", Message: "coding horror story", Keywords: []string{"devops", "failures"}, Tags: []string{"Life", "Tech"}, Slug: "coding-horror-stories", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "The Hidden Science Behind UX", Content: "Your scroll behavior is more predictable than you think. Let's decode that.", Summary: "Human behavior in pixels.", Message: "ux science", Keywords: []string{"ux", "behavioral science"}, Tags: []string{"Science", "Education"}, Slug: "science-of-ux", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Turning Travel Into Tech Inspiration", Content: "A trip to Kyoto helped me redesign a form flow. Here’s why.", Summary: "When beauty informs interface.", Message: "travel inspires tech", Keywords: []string{"travel", "ux", "inspiration"}, Tags: []string{"Travel", "Art"}, Slug: "tech-inspired-by-travel", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Why Business Leaders Should Learn Git", Content: "Merge conflicts are surprisingly good metaphors for meetings.", Summary: "Version control for real life.", Message: "git for business", Keywords: []string{"git", "business", "leaders"}, Tags: []string{"Business", "Education"}, Slug: "business-leaders-git", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Can Video Games Make You Smarter?", Content: "From puzzle logic to resource management, let’s explore the benefits.", Summary: "Gaming isn’t just fun—it’s brain fuel.", Message: "video games and brain", Keywords: []string{"games", "intelligence", "education"}, Tags: []string{"Entertainment", "Education"}, Slug: "games-smart", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "The Future of Work is Weird", Content: "Zoom meetings in VR? AI coworkers? Let’s look at what's coming next.", Summary: "Remote work gets surreal.", Message: "future of work", Keywords: []string{"work", "future", "remote"}, Tags: []string{"Tech", "News"}, Slug: "future-of-work-weird", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "How Music Affects Coding Flow", Content: "Lo-fi or death metal? Here’s what science says about your playlist.", Summary: "Soundtrack your sprint.", Message: "music coding focus", Keywords: []string{"music", "productivity"}, Tags: []string{"Science", "Life"}, Slug: "music-for-coders", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Startup Lessons From Stand-Up Comedy", Content: "Timing, failure, and reading the room. Founders and comedians have a lot in common.", Summary: "Business wisdom from the mic.", Message: "comedy and startups", Keywords: []string{"startups", "comedy", "pitching"}, Tags: []string{"Business", "Entertainment"}, Slug: "startup-standup", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "A Dev’s Guide to Healthy Wrists", Content: "We code with our hands—so let’s not destroy them. Ergonomic wins inside.", Summary: "Save your joints. Code longer.", Message: "healthy wrists for devs", Keywords: []string{"ergonomics", "health", "tech"}, Tags: []string{"Health", "Education"}, Slug: "dev-wrist-health", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Rebuilding the Internet With Art", Content: "Web design is dead. Long live web expression.", Summary: "Creative coding and visual rebellion.", Message: "art and the internet", Keywords: []string{"art", "web", "expression"}, Tags: []string{"Art", "Tech"}, Slug: "internet-as-canvas", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
		models.Post{ID: primitive.NewObjectID(), UserID: primitive.NewObjectID(), Topic: "Your Brain on Notifications", Content: "Ping. Ping. Panic. Let’s talk dopamine and distraction.", Summary: "Science behind attention overload.", Message: "notifications and dopamine", Keywords: []string{"notifications", "focus", "neuroscience"}, Tags: []string{"Science", "Health"}, Slug: "dopamine-notifications", Views: 0, CreatedBy: "Seeder", CreatedAt: now, UpdatedAt: now},
	}

	_, err := postsCollection.InsertMany(ctx, posts)
	if err != nil {
		return err
	}

	log.Printf("✅ Seeded %d posts successfully", len(posts))
	return nil
}
